- jollystation.dme
- jollystation_modules/code/datums/traits/good.dm
- jollystation_modules/code/datums/traits/negative.dm
If you want to rebalance quirk values, look no further than here.
It's as simple as adding in the typepath of the quirk you want to edit in the proper files and adding in a new value.
A few have been added as examples.
> Framework for quirk value rebalancing

- jollystation_modules/code/datums/traits/neutral.dm
As requested, size quirks now offset the player to align with  to the tile.
> Size quirk y offsets

- _maps/map_files/LimaStation/LimaStation.dmm
unheccs a few things temporarily, will make proper fixes later.
> some small lima fixes.

- jollystation_modules/code/modules/mob/living/carbon/human/human.dm
In my defense, why were they all admin only in the first place?
> Makes flavor hrefs actually reachable by players

- code/__DEFINES/chat.dm
- jollystation_modules/code/modules/client/verbs/looc.dm
- tgui/packages/tgui-panel/chat/constants.js
- Minor inconsequential bug fixes for LOOC.
- LOOC can now be filtered to its own chat tag (credit to podrius)
- LOOC now has it's own color to distinguish it from OOC.
> Looc adjustments

- jollystation_modules/code/modules/client/verbs/looc.dm
I removed this variable because I thought it wasn't used. It was used. It didn't show up in LOCAL testing. It did show up on live.
> Fixes LOOC again for real

- tgstation.dme
This isn't actually a problem yet but it maybe probably will be in the future. I don't recommend merging this UNTIL you're about to upstream merge.
> untaints tgstation.dme

- code/__DEFINES/misc.dm
- code/modules/mob/living/carbon/human/species.dm
- jollystation.dme
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
_ʷᵉʰˢ ᶦⁿ ᵗʰᵉ ᵈᶦˢᵗᵃⁿᶜᵉ_
The lizard agenda is forcing me, please help. United states processing facility 287, floor basement 17, third door on the right
:cl:
add: Hairlizard
/:cl:
> [Semi-Modular] Hairlizard Moment

- code/modules/mob/living/carbon/human/species.dm
> Fixes grey lizard horns (?)

- jollystation.dme
- jollystation_modules/code/__DEFINES/examine_defines.dm
- jollystation_modules/code/datums/elements/unique_examine.dm
- jollystation_modules/code/game/objects/items.dm
with the power of god AND elements on my side, I bring this mediocre skyrat code into the future
unique stuff on examine is now handled by ELEMENT!
you can put multiple of these elements on ANY ATOM now! isn't that badass? god I love elements and good code
Now, any mob, object, or whatever you want can be given any sort of unique message and criteria based on any variety of checks! Tons of examples have been included.
> Refactors the examine stuff port to be not bad

- code/__DEFINES/misc.dm
- code/modules/mob/living/carbon/human/species.dm
- jollystation.dme
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/humans.dm
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Reverts #23, #30, and #32
This isn't personal or anything, but hairlizards are fucking broken and need a better implementation before they should be re-implemented. Just continue with wigs as the ancestors did before us.
> Reverts hairlizards (for now)

- _maps/map_files/LimaStation/LimaStation.dmm
updated sec, recent repaths done.
the life of a maptainer is generally considered short and hard, as many m*ppers are driven to insanity before their middle ages.
:cl:
fix: lima repathed to current standards,
tweak: lima sec updated.
/:cl:
> Repath updates, tweaks. Port from sqnztb/tgstation

- jollystation_modules/code/modules/language/highdraconic.dm
> Fix bots speaking high draconic

- jollystation_modules/code/modules/mob/living/carbon/human/species_types/felinid.dm
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/flypeople.dm
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
> Lowers felinid sounds and nukes some nasty space indentation

- .github/workflows/ci_suite.yml
Hopefully makes our checks compile correctly.
> Messes with out CI suite

- jollystation_modules/code/datums/quirks/good.dm
Adds a 2 point positive quirk. You spawn without an appendix. That's it.
> Positive quirk: No appendix

- jollystation_modules/code/modules/jobs/job_types/bridge_officer.dm
- jollystation_modules/code/modules/jobs/job_types/toxicologist.dm
- jollystation_modules/code/modules/jobs/job_types/xenobiologist.dm
please stop touching everything oh my god
- jobs now have plasmaman suits integrated into the job datums
> More modular job fixes

- tgui/yarn.lock
- tools/build/build.js
wait for checks to pass first to see if it really works, kthnx
> makes master compile

- jollystation_modules/code/modules/research/techweb/all_nodes.dm
banish phazons to the heck realm because i hate fun
it isn't
:cl:
balance: phazon research now requires illegal tech research
/:cl:
> Lock phazons behind illegal tech

- .gitignore
- config/dbconfig.txt
> More maintenance 

- code/modules/jobs/job_types/scientist.dm
- jollystation_modules/code/modules/jobs/job_types/bridge_officer.dm
- jollystation_modules/code/modules/jobs/job_types/toxicologist.dm
- jollystation_modules/code/modules/jobs/job_types/xenobiologist.dm
Ok here goes.
- Bridge Officer - Has mostly donuts. Copied over a base sec officers stuff. They also have a chance to - get this - get a box of them.
- Toxicologist - Copied over scientist anomaly core. They can also get a TTV at an exceedingly rare chance, and plasma/oxygen tanks.
-  Xenobiologist - Chance to get a slime extract, box of monkey cubes and some of the deeper beakers.
- Scientist - Altered their mail chances for core and tech disk
> Adds mailing list to our jobs

- jollystation.dme
- jollystation_modules/code/datums/greyscale/json_configs/greyscale_configs.dm
- jollystation_modules/code/datums/greyscale/json_configs/pda_stripe_two_color.json
- jollystation_modules/code/game/objects/items/devices/PDA/PDA_types.dm
- jollystation_modules/code/modules/jobs/job_types/toxicologist.dm
- jollystation_modules/code/modules/jobs/job_types/xenobiologist.dm
Toxicologist and Xenobiologist PDAs. That's it. For once, a PR of mine doesn't have a million un-related changes.
Left is Xenobio. Right is Toxins. Colors literally lifted right off of the clothing.
> Toxicologist and Xenobio PDAs (via GAGS)

- jollystation_modules/code/game/objects/items/devices/PDA/PDA_types.dm
`This proc adds modular PDAs into the PDA painter. Don't forget to update it or else you can't paint added PDAs.`
> Lets you paint the new PDAs

- code/modules/vending/megaseed.dm
- jollystation_modules/code/modules/hydroponics/grown/beans.dm
Per feedback from jolly in #55
It's not.
:cl:
add: leemabeens
/:cl:
> Adds Leemabeens
